# Change these first
owner: LarsK1 # Your GitHub organization or username, where this repository lives
repo: monitoring # The name of this repository

sites:
  - name: Blumagine
    url: https://blumagine.de
  - name: Monitoring
    url: https://monitoring.blumagine.de
  - name: E-Mail-Security
    url: https://security.blumagine.de

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /monitoring
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime**, immer eine sichere Sache"
  introMessage: Das ist unsere zweite Uptime-Überwachung
  navbar:
    - title: Status
      href: /
    - title: Blumagine
      href: https://blumagine.de
assignees:
  - LarsK1

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
